---
title: "Phloem Feeding Insects Inhibit Caterpillar Parasitism"
author: "Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
  html_document:
    keep_md: yes
    theme: readable
  html_notebook:
    code_folding: hide
    theme: readable
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```





```{r Main_Code, include = F, cache = F}

# Load Packages
library(tidyverse) 
library(cowplot) 
library(lme4)
library(knitr)
library(forcats)
library(emmeans)
library(glmmTMB)
library(car)

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets:

dat1 <- read.csv("data/data.19.20.21.22.csv")

####################################################
#                    Functions                     #
####################################################


# Function to scale the range of values so that they are always positive or always negative, respectively

range01 <- function(x){
  (x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))
  }

```


# Overview


```{r Data_Wrangling, echo = F, comment = ""}

dat1 <- dat1 %>% 
  mutate(across(c(branchID : para), as.factor),
         para = as.numeric(para) - 1)

```



# Ants and Phloem-feeders:

## GLMM approach
```{r pf_ant_glmm, echo = F}


mod1.interaction <- glmmTMB(para ~ pf_treatment * ant_treatment +
                     year + (1 | site) + (1 | cat_species),
                   family = binomial(),
                   contrasts = list(year = "contr.sum"),
                data = filter(dat1, year == "2019" | year == "2022"))
                # doesn't converge with data = dat1


# Likelihood ratio tests:
mod2.additive.only <- update(mod1.interaction, ~ . -pf_treatment : ant_treatment)

mod3.pf.only <- update(mod2.additive.only, ~ . -ant_treatment)

mod4.no.pf <- update(mod3.pf.only, ~ . -pf_treatment)

results <- as_tibble(anova(mod1.interaction,
                           mod2.additive.only,
                           mod3.pf.only, mod4.no.pf,
                           test = "LRT"),
                     rownames = "LRT_models")

lrt.names <- c("Null model", "Phloem-feeders",
               "Phloem-feeders + Ants",
               "Phloem-feeders x Ants")

results <- results %>% 
  mutate(LRT_models = lrt.names)

results

kable(results, format = "markdown", digits = 3)

```


```{r pf_glmm_Robi, echo = F}

 
## don't include ant_treatment as a random effect. With 2 levels it's 
## meaningless. Just leave it out or include as a fixed effect (perhaps 
## make it sum-to-zero contrasts so other coefficients are expressed at 
## their sum
## Could also make that argument for year (note that year has a 
## vanishingly small effect, which is throwing the errors in glmer

# pf.mod <- glmmTMB(para ~ year + pf_treatment + 
#                     (1 | site) + (1 | cat_species),
#                   data = dat1, family = binomial(),
#                   contrasts = list(year = "contr.sum"))
# 
# 
# summary(pf.mod) # doesn't work
# 
# 
# ## use likelihood ratio test
# pf.mod0 <- update(pf.mod, ~.-pf_treatment)
# anova(pf.mod, pf.mod0) ## very strong reduction of deviance with addition of 
# ## pf treatment
# sims <- simulate(pf.mod0, 10)
# ## bootstrap
# nsim <- 99
# dev_pf <- deviance(pf.mod0) - deviance(pf.mod)
# test <- sapply(1:nsim, function(i, mod0, mod1){
#   new_y <- simulate(mod0)[,1]
#   mod0_new <- refit(mod0, new_y)
#   mod1_new <- refit(mod1, new_y)
#   dev <- deviance(mod0_new) - deviance(mod1_new)
#   return(dev)
# }, mod0 = pf.mod0, mod1 = pf.mod)
# 
# sum(test > deviance(pf.mod0) - deviance(pf.mod))/(nsim + 1)
# hist(test, xlim = c(0, max(dev_pf, test)*1.5)); abline(v = dev_pf)
# 
# 
# 
# anova(pf.mod, pf.mod0, test = "LRT")
```

# Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


